language: php

php:
  - 5.5

before_script:
  - cp .env.travis .env
  - mysql -e 'create database sigeo;'
  - npm install
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit